name: del-runs-comments
on: workflow_dispatch
jobs:
  runx:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: christosgalano/delete-workflow-runs@v1.0.0
        with:
          owner: mapx-
          repo: test
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: run-script
          
          


    
    