name: run-script
on: workflow_dispatch
jobs:
  runx:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v1
      - name: script
        env:
          GH_TOKEN: ${{ github.token }}
        run: | 
           chmod +x ".github/delete-logs.sh"
           .github/delete-logs.sh mapx-/test test.yml
           shell: bash
          
          


