name: run-script
on: workflow_dispatch
jobs:
  runx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: script
        run: .github/delete-logs.sh
        shell: bash
          
          


