name: run-script
on: workflow_dispatch
jobs:
  runx:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions-cool/issues-helper@v3
      - name: script
        run: | 
           chmod +x ".github/delete-logs.sh"
           .github/delete-logs.sh
           shell: bash
          
          


