on:
  issue_comment:
    types: created
jobs:
  check-if-bad-comment:
    name: delete bad comment
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'baubau') && contains(github.event.comment.body, 'xyx')
    permissions:
      issues: write
    steps:
      - run: echo ${{ github.event.comment.body }}
             echo ${{ github.event.comment.id }}
      - name: Delete comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'delete-comment'
          comment-id: ${{ github.event.comment.id }}
