on:
  issue_comment:
    types: created
jobs:
  check-if-bad-comment:
    name: delete bad comment
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'baubau') && contains(github.event.comment.body, 'xyx')
    permissions:
      issues: write
    steps:
      - run: echo ${{ github.event.comment.body }}
             echo ${{ github.event.comment.id }}
    
